# Database connection for Development
spring.datasource.url=jdbc:mysql://localhost:3306/TrainManagement
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate specific to Development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG


#jwt
jwt.secret=8F4D6A1B9E2C7D5F3A8B6C9D1E4F7A2B8C5D9E1F6A3B7C2D4E8F1A5B9C6D2E7
jwt.expiration=3600000